services:
  # Laravel API Backend
  api:
    container_name: ProjectWork-BE
    build:
      context: ../ProjectWork-BE
      dockerfile: Dockerfile

    hostname: ProjectWork-BE
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ../ProjectWork-BE:/var/www/html
      - /var/www/html/vendor
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=project_work_db
      - DB_USERNAME=project_work_user
      - DB_PASSWORD=project_work_password
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - project_work-network

  # React Frontend
  frontend:
    build:
      context: ../ProjectWork-FE
      dockerfile: Dockerfile
      target: development
    container_name: ProjectWork-FE
    restart: unless-stopped
    volumes:
      - ../ProjectWork-FE:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    depends_on:
      - api
    networks:
      - project_work-network

  # MySQL Database
  db:
    container_name: ProjectWork-DB
    image: container-registry.oracle.com/mysql/community-server:8.0
    command: --default-authentication-plugin=mysql_native_password --sql-mode="NO_ENGINE_SUBSTITUTION"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: project_work_db
      MYSQL_USER: project_work_user
      MYSQL_PASSWORD: project_work_password
      MYSQL_ROOT_PASSWORD: root_password
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    networks:
      - project_work-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  project_work-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  frontend_node_modules:
    driver: local 